### ISSUE TITLE
HF app has error

### ISSUE THREAD

**Issue by robmarkcole** [mayrajeo/ship-detection#2]
https://huggingface.co/spaces/mayrajeo/marine-vessel-detection/tree/main

Likely due to unpinned requirements. I have 
```
ultralytics==8.2.57
plotly==5.22.0
sahi==0.11.18
onnxruntime==1.18.1
gradio==4.38.1
``` 
and needed to comment a line in `sahi_onnx.py`:
```
# bool_mask=None,
```
then no issues

**Comment by mayrajeo** [comment]
Thanks for the info, seems that it's what you get when you update things just before you leave for summer holiday. Error was due to a recent sahi version update, and another way to fix is to replace `bool_mask` with `segmentation`. Should be fixed now.
